### ISSUE TITLE
Windows.PY Problems

### ISSUE THREAD

**Issue by gunner007cd** [Plailect/OTP#2]
Currently Windows.PY has incorrect syntax. It is expecting 3DSFAT16TOOL to reside in the same working folder.

Also fails to move the files. Temporary workaround is just to copy the resource folder files to the root of Bricked and run it. Then rename the file manually and move to Unbricked.

I'll edit the windows.py with the correct syntax and push when I have some time.

Edit: This is for N3DS with CN

**Comment by Plailect** [comment]
Fixed with r2.1
