### ISSUE TITLE
New 3DS OTP All In One Pack download missing

### ISSUE THREAD

**Issue by MKWPlayer1337** [Plailect/OTP#21]
Whenever I try to get the All In One Pack for the N3DS OTP process, it says "Not Found". Has it been removed? Please let me know if there is an alternative download link for this. Thanks!

**Comment by Plailect** [comment]
This method of getting the OTP is dangerous, outdated, and unsupported. All packs have been removed, and you should follow the main guide instead.

https://github.com/Plailect/Guide/wiki

**Comment by MKWPlayer1337** [comment]
Oh okay. How would I unbrick my new 3DS once the emuNAND gets downgraded to 2.1?

**Comment by Plailect** [comment]
The latest version of OTPhelper has a One Click Setup to do everything,
Part 4 of the new guide deals with how to use it.

**Comment by MKWPlayer1337** [comment]
ok. great. Thank you very much.
