### ISSUE TITLE
Getting an error when trying to move my emuNAND from 2GB SD to 16GB SD

### ISSUE THREAD

**Issue by TheAzure289** [Plailect/OTP#22]
Hi again Plailect, I keep getting this error when I try to Extract my emuNAND using EmuNAND tool. I have the SD card I've been using for all of this inside the reader so I have no Idea why it can't see it?

error:
http://i.imgur.com/DnMHMHu.png?1

I only got up to step 22 of part 4 "getting the OTP", and didn't have enough space left on the card (590 mb left of 2 GB). Please give me step by step trouble shoot because I'm not finding anything that makes sense on google.

**Comment by Plailect** [comment]
It may not support RedNAND, you'll have to check where you downloaded it.

**Comment by TheAzure289** [comment]
I got it from this link: https://gbatemp.net/threads/emunand-tool-release-and-support-thread.359239/ 

You gave me the link in the thread you closed, would you happen to know of a emunand tool that does support rednand?

**Comment by Plailect** [comment]
You're extracting from the SD that already has the EmuNAND right?

**Comment by TheAzure289** [comment]
Yes, the 2GB SD is the one I'm trying to extract from. It's the one I set everything up with and I'm trying to copy all of that to the 16GB SD. Is there a way to restart the whole process and start again with the 16GB?

**Comment by Plailect** [comment]
May not support rednand actually. Try
https://gbatemp.net/threads/release-3ds-multi-emunand-creator.381603/

**Comment by TheAzure289** [comment]
Ok I've downloaded that but now I'm here and can't make heads or tales of it?

http://i.imgur.com/9AzHdb1.png

http://i.imgur.com/CWsw653.png

Where do I find what it's asking me to find in the second picture? Sorry if I'm being a pain, I wouldn't mind starting all over if there is a way?

**Comment by Plailect** [comment]
You're just choosing what you want the output file to be called.

**Comment by TheAzure289** [comment]
I just typed "emu" for a test try and got this error: http://i.imgur.com/c21PQ0d.png

I went to try to format emunand but it's greyed out:

http://i.imgur.com/7dO8tuc.png

This SD is the only one I've been using for all of this, I haven't removed or altered it outside of your guide. :(

**Comment by TheAzure289** [comment]
Hey dude, figure anything out?

**Comment by Plailect** [comment]
Just redo part 3 with a different SD, it's probably the simplest solution
