### ISSUE TITLE
Minor suggestion for Tutorial

### ISSUE THREAD

**Issue by fallenlucario** [Plailect/OTP#5]
Just a minor thing I feel is misplaced. Section 2 Step 1 says to delete any previously made updates folder. I feel it would be better in section 1 (before the "copy all sd files" step) due to the section_I folder containing an updates folder. This would prevent accidental merging of a previous updates folder's contents with the new updates folder containing the v2.1 files.

**Comment by Plailect** [comment]
The updates folder was moved to section II's copy_to_sd_card folder recently, so the instruction is in the right spot.

**Comment by fallenlucario** [comment]
Ah, that seemed more fitting! I was going to suggest that as well but it seemed like more of a hassle to repackage and upload all the packs than to change the written guide. Awesome work though and thank you very much for the tutorial!
