### ISSUE TITLE
Section II Linux.sh/Mac.sh script incorrectly references "nand.fat16.xorpad" when checking if "nand.fat16.0x4.xorpad" file exist

### ISSUE THREAD

**Issue by SoujiSeta** [Plailect/OTP#6]
The linux.sh shell script for applying the xorpads against the emuNAND_bricked.bin dump
has this if check for "nand.fat16.0x4.xorpad"

if [ ! -f ../../Section_I/Backup/**nand.fat16.xorpad** ]; then
    echo "Could not find nand.fat16.0x4.xorpad in Section_I/Backup!"
    exit 1
fi

where it should be
if [ ! -f ../../Section_I/Backup/**nand.fat16.0x4.xorpad** ]; then
    echo "Could not find nand.fat16.0x4.xorpad in Section_I/Backup!"
    exit 1
fi

**Comment by Plailect** [comment]
Fixed
